# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\PythonTest\StudingZone\GUI_PyQt5_logging.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 601, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_TestLog = QtWidgets.QWidget()
        self.tab_TestLog.setObjectName("tab_TestLog")
        self.frame = QtWidgets.QFrame(self.tab_TestLog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 591, 561))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout.addWidget(self.btn_browse)
        self.txt_fDir = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.txt_fDir.setObjectName("txt_fDir")
        self.horizontalLayout.addWidget(self.txt_fDir)
        self.cb_filetype = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.cb_filetype.setObjectName("cb_filetype")
        self.cb_filetype.addItem("")
        self.cb_filetype.addItem("")
        self.cb_filetype.addItem("")
        self.cb_filetype.addItem("")
        self.horizontalLayout.addWidget(self.cb_filetype)
        self.txt_log = QtWidgets.QTextBrowser(self.frame)
        self.txt_log.setGeometry(QtCore.QRect(10, 90, 341, 451))
        self.txt_log.setObjectName("txt_log")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 201, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_start = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_2.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_2.addWidget(self.btn_stop)
        self.lv_folder = QtWidgets.QListView(self.frame)
        self.lv_folder.setGeometry(QtCore.QRect(360, 90, 221, 301))
        self.lv_folder.setObjectName("lv_folder")
        self.btn_load = QtWidgets.QPushButton(self.frame)
        self.btn_load.setGeometry(QtCore.QRect(510, 60, 75, 23))
        self.btn_load.setObjectName("btn_load")
        self.txt_fileoutput = QtWidgets.QTextBrowser(self.frame)
        self.txt_fileoutput.setGeometry(QtCore.QRect(360, 430, 221, 111))
        self.txt_fileoutput.setObjectName("txt_fileoutput")
        self.lb_fileoutput = QtWidgets.QLabel(self.frame)
        self.lb_fileoutput.setGeometry(QtCore.QRect(360, 410, 91, 16))
        self.lb_fileoutput.setObjectName("lb_fileoutput")
        self.lb_count = QtWidgets.QLabel(self.frame)
        self.lb_count.setGeometry(QtCore.QRect(360, 70, 56, 12))
        self.lb_count.setObjectName("lb_count")
        self.tabWidget.addTab(self.tab_TestLog, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_browse.setText(_translate("MainWindow", "browse.."))
        self.cb_filetype.setItemText(0, _translate("MainWindow", "txt"))
        self.cb_filetype.setItemText(1, _translate("MainWindow", "hwp"))
        self.cb_filetype.setItemText(2, _translate("MainWindow", "xlsx"))
        self.cb_filetype.setItemText(3, _translate("MainWindow", "docx"))
        self.btn_start.setText(_translate("MainWindow", "Start Logging.."))
        self.btn_stop.setText(_translate("MainWindow", "Stop Logging"))
        self.btn_load.setText(_translate("MainWindow", "Load Folder"))
        self.lb_fileoutput.setText(_translate("MainWindow", "File output:"))
        self.lb_count.setText(_translate("MainWindow", "count :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_TestLog), _translate("MainWindow", "Test Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
