# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\PythonTest\StudingZone\EncodingDecoding\GUI_File_encoding.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 240)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 25 9pt \"나눔스퀘어라운드 Light\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_file.setGeometry(QtCore.QRect(10, 8, 75, 23))
        self.btn_file.setObjectName("btn_file")
        self.txt_file = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_file.setGeometry(QtCore.QRect(90, 9, 321, 20))
        self.txt_file.setObjectName("txt_file")
        self.btn_encoding = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encoding.setGeometry(QtCore.QRect(10, 79, 401, 131))
        self.btn_encoding.setStyleSheet("background-color: rgb(254, 210, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 25 20pt \"나눔스퀘어라운드 Light\";")
        self.btn_encoding.setObjectName("btn_encoding")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setGeometry(QtCore.QRect(10, 34, 401, 41))
        self.horizontalFrame.setStyleSheet("background-color: rgb(255, 243, 253);")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_createUser = QtWidgets.QPushButton(self.horizontalFrame)
        self.btn_createUser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_createUser.setObjectName("btn_createUser")
        self.horizontalLayout.addWidget(self.btn_createUser)
        self.txt_getID = QtWidgets.QComboBox(self.horizontalFrame)
        self.txt_getID.setObjectName("txt_getID")
        self.horizontalLayout.addWidget(self.txt_getID)
        self.txt_getSalt = QtWidgets.QLineEdit(self.horizontalFrame)
        self.txt_getSalt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_getSalt.setObjectName("txt_getSalt")
        self.horizontalLayout.addWidget(self.txt_getSalt)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_file.setText(_translate("MainWindow", "File .."))
        self.btn_encoding.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>ㅇㅇㅇ</p></body></html>"))
        self.btn_encoding.setText(_translate("MainWindow", "Encoding !"))
        self.btn_createUser.setText(_translate("MainWindow", "Create User"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
