# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\PythonTest\StudingZone\EncodingDecoding\GUI_Decoding.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 313)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 25 11pt \"나눔스퀘어라운드OTF Light\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 511, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_File = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_File.setStyleSheet("background-color: rgb(241, 255, 189);")
        self.btn_File.setObjectName("btn_File")
        self.horizontalLayout.addWidget(self.btn_File)
        self.txt_file = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.txt_file.setObjectName("txt_file")
        self.horizontalLayout.addWidget(self.txt_file)
        self.btn_reload = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_reload.setObjectName("btn_reload")
        self.horizontalLayout.addWidget(self.btn_reload)
        self.lv_filelist = QtWidgets.QListView(self.centralwidget)
        self.lv_filelist.setGeometry(QtCore.QRect(20, 50, 221, 211))
        self.lv_filelist.setStyleSheet("background-color: rgb(230, 255, 234);")
        self.lv_filelist.setObjectName("lv_filelist")
        self.txt_result = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_result.setGeometry(QtCore.QRect(250, 50, 281, 211))
        self.txt_result.setObjectName("txt_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_File.setText(_translate("MainWindow", "File..."))
        self.btn_reload.setText(_translate("MainWindow", "Reload"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
